-- Tests for longway.api.search
local t = require("longway-spec.init")
local search = require("longway.api.search")

local function _1_()
  before_each(function() t.setup_test_config({}) end)

  describe("search_stories", function()
    it("is a function", function()
      assert.is_function(search.search_stories)
    end)
  end)

  describe("search_stories_all", function()
    it("is a function", function()
      assert.is_function(search.search_stories_all)
    end)
  end)

  describe("search_epics", function()
    it("is a function", function()
      assert.is_function(search.search_epics)
    end)
  end)

  describe("build_query", function()
    it("is a function", function()
      assert.is_function(search.build_query)
    end)
    it("builds query from simple filters", function()
      local query = search.build_query({ owner = "me", type = "feature" })
      assert.is_string(query)
      assert.truthy(string.find(query, "owner:me"))
      assert.truthy(string.find(query, "type:feature"))
    end)
    it("quotes values with spaces", function()
      local query = search.build_query({ state = "In Progress" })
      assert.truthy(string.find(query, "\"In Progress\""))
    end)
  end)

  describe("parse_query", function()
    it("is a function", function()
      assert.is_function(search.parse_query)
    end)
    it("parses key:value pairs", function()
      local result = search.parse_query("owner:me state:started")
      assert.is_table(result)
      assert.is_table(result.params)
    end)
  end)
end

return describe("longway.api.search", _1_)
